project:
  type: website
  output-dir: docs

website:
  title: "website"
  navbar:
    pinned: true
    left:
      - href: life-gdp.qmd
        text: Life Expectancy and GDP per Capita
      - href: life-population.qmd
        text: Life Expectancy and Population
      - href: country.qmd
        text: Country Analysis

format:
  html:
    theme:
      - darkly
    css: styles.css
    toc: true



